- name: check if qarax-node was built
  stat:
    path: $HOME/qarax-node
  register: qarax_node

- name: compile local qarax-node
  shell: cargo build
  args:
    chdir: "{{ local_node_path }}"
  delegate_to: localhost
  when: local_node_path is defined

- name: copy qarax-node binary
  copy:
    # TODO: maybe build it directly somewhere else
    src: "{{ local_node_path }}/target/debug/qarax-node"
    dest: $HOME/
  when: local_node_path is defined

- name: set correct permissions to qarax-node
  file:
    path: $HOME/qarax-node
    mode: "u+x"

- name: check if qarax-node is running
  command: pgrep qarax-node
  register: qarax_node_running
  ignore_errors: true

- name: check qarax-node pgrep
  debug:
    msg: "{{ qarax_node_running }}"

- name: copy qarax_node_running.sh to host
  copy:
    src: ./files/start_qarax_node.sh
    dest: start_qarax_node.sh
    mode: u=rwx

- name: start qarax-node
  command: ./start_qarax_node.sh
  async: 10
  poll: 0
  when: qarax_node_running.rc == 1
