- name: clone firecracker repo
  git:
    repo: 'https://github.com/firecracker-microvm/firecracker'
    dest: src/firecracker
    force: yes

- name: check if binary exists
  stat:
    path: src/firecracker/build/release/firecracker
  register: binary_exists

# TODO: remove this, I don't think it's going to be used
- name: build firecracker from source
  shell: src/firecracker/tools/devtool build --release
  when: binary_exists.stat.exists == False


