# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.models.health_response import HealthResponse  # noqa: E501
from qarax.rest import ApiException


class TestHealthResponse(unittest.TestCase):
    """HealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthResponse(self):
        """Test HealthResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qarax.models.health_response.HealthResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
