# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import qarax
from qarax.models.post_response import PostResponse  # noqa: E501
from qarax.rest import ApiException

class TestPostResponse(unittest.TestCase):
    """PostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = qarax.models.post_response.PostResponse()  # noqa: E501
        if include_optional :
            return PostResponse(
                id = '0'
            )
        else :
            return PostResponse(
        )

    def testPostResponse(self):
        """Test PostResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
