# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.models.storage import Storage  # noqa: E501
from qarax.rest import ApiException


class TestStorage(unittest.TestCase):
    """Storage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorage(self):
        """Test Storage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qarax.models.storage.Storage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
