# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.install_host import InstallHost  # noqa: E501
from swagger_client.rest import ApiException


class TestInstallHost(unittest.TestCase):
    """InstallHost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstallHost(self):
        """Test InstallHost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.install_host.InstallHost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
