# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qarax
from qarax.api.drives_api import DrivesApi  # noqa: E501
from qarax.rest import ApiException


class TestDrivesApi(unittest.TestCase):
    """DrivesApi unit test stubs"""

    def setUp(self):
        self.api = qarax.api.drives_api.DrivesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_drive(self):
        """Test case for add_drive

        Add new drive  # noqa: E501
        """
        pass

    def test_list_drives(self):
        """Test case for list_drives

        Get drives list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
