# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qarax
from qarax.api.kernels_api import KernelsApi  # noqa: E501
from qarax.rest import ApiException


class TestKernelsApi(unittest.TestCase):
    """KernelsApi unit test stubs"""

    def setUp(self):
        self.api = qarax.api.kernels_api.KernelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_kernel(self):
        """Test case for add_kernel

        Add new kernel  # noqa: E501
        """
        pass

    def test_get_kernel_storage(self):
        """Test case for get_kernel_storage

        """
        pass

    def test_list_kernel(self):
        """Test case for list_kernel

        get kernels list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
