# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.api.storage_api import StorageApi  # noqa: E501
from qarax.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_get(self):
        """Test case for storage_get

        get storages list  # noqa: E501
        """
        pass

    def test_storage_post(self):
        """Test case for storage_post

        Add new storage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
