# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import qarax
from qarax.models.vm import Vm  # noqa: E501
from qarax.rest import ApiException

class TestVm(unittest.TestCase):
    """Vm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Vm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = qarax.models.vm.Vm()  # noqa: E501
        if include_optional :
            return Vm(
                address = '0', 
                host_id = '0', 
                id = '0', 
                kernel = '0', 
                kernel_params = '0', 
                memory = 56, 
                name = '0', 
                network_mode = '0', 
                status = 56, 
                vcpu = 56
            )
        else :
            return Vm(
        )

    def testVm(self):
        """Test Vm"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
