# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.api.kernels_api import KernelsApi  # noqa: E501
from qarax.rest import ApiException


class TestKernelsApi(unittest.TestCase):
    """KernelsApi unit test stubs"""

    def setUp(self):
        self.api = KernelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_kernels_get(self):
        """Test case for kernels_get

        get kernels list  # noqa: E501
        """
        pass

    def test_kernels_kernel_id_storage_get(self):
        """Test case for kernels_kernel_id_storage_get

        """
        pass

    def test_kernels_post(self):
        """Test case for kernels_post

        Add new kernel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
