# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.models.post_response import PostResponse  # noqa: E501
from qarax.rest import ApiException


class TestPostResponse(unittest.TestCase):
    """PostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostResponse(self):
        """Test PostResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qarax.models.post_response.PostResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
