# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qarax
from qarax.api.storage_api import StorageApi  # noqa: E501
from qarax.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = qarax.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_storage(self):
        """Test case for add_storage

        Add new storage  # noqa: E501
        """
        pass

    def test_list_storage(self):
        """Test case for list_storage

        get storages list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
