# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qarax
from qarax.models.host import Host  # noqa: E501
from qarax.rest import ApiException


class TestHost(unittest.TestCase):
    """Host unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHost(self):
        """Test Host"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qarax.models.host.Host()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
