# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import qarax
from qarax.models.host import Host  # noqa: E501
from qarax.rest import ApiException

class TestHost(unittest.TestCase):
    """Host unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Host
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = qarax.models.host.Host()  # noqa: E501
        if include_optional :
            return Host(
                address = '0', 
                host_user = '0', 
                id = '0', 
                name = '0', 
                password = '0', 
                port = 56, 
                status = '0'
            )
        else :
            return Host(
        )

    def testHost(self):
        """Test Host"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
