# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qarax
from qarax.api.hosts_api import HostsApi  # noqa: E501
from qarax.rest import ApiException


class TestHostsApi(unittest.TestCase):
    """HostsApi unit test stubs"""

    def setUp(self):
        self.api = qarax.api.hosts_api.HostsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_host(self):
        """Test case for add_host

        Create new host  # noqa: E501
        """
        pass

    def test_get_host(self):
        """Test case for get_host

        Get host by ID  # noqa: E501
        """
        pass

    def test_health_check(self):
        """Test case for health_check

        Host health check  # noqa: E501
        """
        pass

    def test_install_host(self):
        """Test case for install_host

        Install qarax node on host  # noqa: E501
        """
        pass

    def test_list_hosts(self):
        """Test case for list_hosts

        Get hosts list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
