# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qarax
from qarax.api.v_ms_api import VMsApi  # noqa: E501
from qarax.rest import ApiException


class TestVMsApi(unittest.TestCase):
    """VMsApi unit test stubs"""

    def setUp(self):
        self.api = qarax.api.v_ms_api.VMsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_vm(self):
        """Test case for add_vm

        Add new VM  # noqa: E501
        """
        pass

    def test_attach_drive(self):
        """Test case for attach_drive

        Add drive to VM  # noqa: E501
        """
        pass

    def test_get_vm(self):
        """Test case for get_vm

        VM details  # noqa: E501
        """
        pass

    def test_list_vm_drives(self):
        """Test case for list_vm_drives

        """
        pass

    def test_list_vms(self):
        """Test case for list_vms

        get vms list  # noqa: E501
        """
        pass

    def test_start_vm(self):
        """Test case for start_vm

        Start VM  # noqa: E501
        """
        pass

    def test_stop_vm(self):
        """Test case for stop_vm

        Stop VM  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
