-- Squashed initial migration representing the complete final schema.
-- Generated from migrations 20240330120537 through 20260402000003.
-- Do not edit this file directly.

-- ============================================================
-- UTILITY FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE host_status AS ENUM (
    'UNKNOWN',
    'DOWN',
    'INSTALLING',
    'INSTALLATION_FAILED',
    'INITIALIZING',
    'UP'
);

-- Final vm_status (replaced old UP/DOWN with richer lifecycle)
CREATE TYPE vm_status AS ENUM (
    'UNKNOWN',
    'CREATED',
    'RUNNING',
    'PAUSED',
    'SHUTDOWN',
    'PENDING',
    'MIGRATING',
    'COMMITTING'
);

CREATE TYPE hypervisor AS ENUM (
    'CLOUD_HV',
    'FIRECRACKER',
    'QEMU'
);

CREATE TYPE interface_type AS ENUM (
    'macvtap',
    'tap',
    'vhost_user'
);

-- Final storage_pool_type (LOCAL, NFS, OVERLAYBD only)
CREATE TYPE storage_pool_type AS ENUM (
    'LOCAL',
    'NFS',
    'OVERLAYBD'
);

CREATE TYPE storage_pool_status AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'ERROR'
);

CREATE TYPE storage_object_type AS ENUM (
    'DISK',
    'KERNEL',
    'INITRD',
    'ISO',
    'SNAPSHOT',
    'OCI_IMAGE',
    'OVERLAYBD_UPPER'
);

CREATE TYPE transfer_type AS ENUM ('DOWNLOAD', 'LOCAL_COPY');
CREATE TYPE transfer_status AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');

CREATE TYPE job_type AS ENUM (
    'IMAGE_PULL',
    'VM_START',
    'VM_MIGRATE',
    'DISK_CREATE',
    'VM_COMMIT'
);

CREATE TYPE job_status AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');

CREATE TYPE console_mode AS ENUM (
    'OFF',
    'PTY',
    'TTY',
    'FILE',
    'SOCKET',
    'NULL'
);

CREATE TYPE boot_mode AS ENUM ('KERNEL', 'FIRMWARE');

CREATE TYPE network_status AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TYPE snapshot_status AS ENUM ('CREATING', 'READY', 'FAILED');

CREATE TYPE hook_scope AS ENUM ('GLOBAL', 'VM', 'TAG');

CREATE TYPE hook_execution_status AS ENUM ('PENDING', 'DELIVERED', 'FAILED');

CREATE TYPE sandbox_status AS ENUM ('PROVISIONING', 'READY', 'ERROR', 'DESTROYING');

-- ============================================================
-- TABLES (dependency order: referenced tables first)
-- ============================================================

-- hosts
CREATE TABLE IF NOT EXISTS hosts (
    id                       UUID DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
    name                     VARCHAR(50) UNIQUE NOT NULL,
    address                  VARCHAR(16) UNIQUE NOT NULL,
    port                     INT4 NOT NULL,
    status                   host_status NOT NULL,
    host_user                VARCHAR(32) NOT NULL,
    password                 BYTEA NOT NULL,
    cloud_hypervisor_version TEXT,
    kernel_version           TEXT,
    total_cpus               INT,
    total_memory_bytes       BIGINT,
    available_memory_bytes   BIGINT,
    load_average             DOUBLE PRECISION,
    disk_total_bytes         BIGINT,
    disk_available_bytes     BIGINT,
    resources_updated_at     TIMESTAMPTZ,
    node_version             TEXT,
    last_deployed_image      TEXT,
    architecture             VARCHAR(16)
);

-- networks
CREATE TABLE IF NOT EXISTS networks (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(50) UNIQUE NOT NULL,
    subnet     CIDR NOT NULL,
    type       VARCHAR(50),
    gateway    INET,
    dns        INET,
    status     network_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_networks_modtime
BEFORE UPDATE ON networks
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- storage_pools (host_id column removed in favour of host_storage_pools join table)
CREATE TABLE IF NOT EXISTS storage_pools (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name            VARCHAR(100) UNIQUE NOT NULL,
    pool_type       storage_pool_type NOT NULL,
    status          storage_pool_status NOT NULL DEFAULT 'INACTIVE',
    config          JSONB NOT NULL DEFAULT '{}'::jsonb,
    capacity_bytes  BIGINT,
    allocated_bytes BIGINT DEFAULT 0,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_capacity CHECK (allocated_bytes <= capacity_bytes OR capacity_bytes IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_storage_pools_type   ON storage_pools(pool_type);
CREATE INDEX IF NOT EXISTS idx_storage_pools_status ON storage_pools(status);

CREATE TRIGGER update_storage_pools_modtime
BEFORE UPDATE ON storage_pools
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- host_storage_pools (many-to-many: hosts ↔ storage_pools)
CREATE TABLE IF NOT EXISTS host_storage_pools (
    host_id         UUID NOT NULL REFERENCES hosts(id) ON DELETE CASCADE,
    storage_pool_id UUID NOT NULL REFERENCES storage_pools(id) ON DELETE CASCADE,
    PRIMARY KEY (host_id, storage_pool_id)
);

CREATE INDEX IF NOT EXISTS idx_host_storage_pools_host ON host_storage_pools(host_id);
CREATE INDEX IF NOT EXISTS idx_host_storage_pools_pool ON host_storage_pools(storage_pool_id);

-- storage_objects
CREATE TABLE IF NOT EXISTS storage_objects (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    storage_pool_id UUID REFERENCES storage_pools(id) NOT NULL,
    object_type     storage_object_type NOT NULL,
    size_bytes      BIGINT NOT NULL,
    config          JSONB NOT NULL DEFAULT '{}'::jsonb,
    parent_id       UUID REFERENCES storage_objects(id),
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(storage_pool_id, name)
);

CREATE INDEX IF NOT EXISTS idx_storage_objects_pool   ON storage_objects(storage_pool_id);
CREATE INDEX IF NOT EXISTS idx_storage_objects_type   ON storage_objects(object_type);
CREATE INDEX IF NOT EXISTS idx_storage_objects_parent ON storage_objects(parent_id);

CREATE TRIGGER update_storage_objects_modtime
BEFORE UPDATE ON storage_objects
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- boot_sources
CREATE TABLE IF NOT EXISTS boot_sources (
    id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name              VARCHAR(100) UNIQUE NOT NULL,
    description       TEXT,
    kernel_image_id   UUID REFERENCES storage_objects(id) NOT NULL,
    kernel_params     TEXT,
    initrd_image_id   UUID REFERENCES storage_objects(id),
    firmware_image_id UUID REFERENCES storage_objects(id),
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_boot_sources_kernel ON boot_sources(kernel_image_id);
CREATE INDEX IF NOT EXISTS idx_boot_sources_initrd ON boot_sources(initrd_image_id);

CREATE TRIGGER update_boot_sources_modtime
BEFORE UPDATE ON boot_sources
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- instance_types
CREATE TABLE IF NOT EXISTS instance_types (
    id                   UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name                 VARCHAR(100) UNIQUE NOT NULL,
    description          TEXT,
    boot_vcpus           INTEGER NOT NULL,
    max_vcpus            INTEGER NOT NULL,
    cpu_topology         JSONB,
    kvm_hyperv           BOOLEAN,
    memory_size          BIGINT NOT NULL,
    memory_hotplug_size  BIGINT,
    memory_mergeable     BOOLEAN,
    memory_shared        BOOLEAN,
    memory_hugepages     BOOLEAN,
    memory_hugepage_size BIGINT,
    memory_prefault      BOOLEAN,
    memory_thp           BOOLEAN,
    accelerator_config   JSONB NOT NULL DEFAULT '{}'::jsonb,
    numa_config          JSONB,
    architecture         VARCHAR(16),
    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_instance_types_modtime
BEFORE UPDATE ON instance_types
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- vm_templates
CREATE TABLE IF NOT EXISTS vm_templates (
    id                       UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name                     VARCHAR(100) UNIQUE NOT NULL,
    description              TEXT,
    hypervisor               hypervisor,
    boot_vcpus               INTEGER,
    max_vcpus                INTEGER,
    cpu_topology             JSONB,
    kvm_hyperv               BOOLEAN,
    memory_size              BIGINT,
    memory_hotplug_size      BIGINT,
    memory_mergeable         BOOLEAN,
    memory_shared            BOOLEAN,
    memory_hugepages         BOOLEAN,
    memory_hugepage_size     BIGINT,
    memory_prefault          BOOLEAN,
    memory_thp               BOOLEAN,
    boot_source_id           UUID REFERENCES boot_sources(id),
    root_disk_object_id      UUID REFERENCES storage_objects(id),
    boot_mode                boot_mode,
    image_ref                TEXT,
    cloud_init_user_data     TEXT,
    cloud_init_meta_data     TEXT,
    cloud_init_network_config TEXT,
    network_id               UUID REFERENCES networks(id),
    networks                 JSONB,
    config                   JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vm_templates_boot_source ON vm_templates(boot_source_id);
CREATE INDEX IF NOT EXISTS idx_vm_templates_root_disk   ON vm_templates(root_disk_object_id);
CREATE INDEX IF NOT EXISTS idx_vm_templates_network     ON vm_templates(network_id);

CREATE TRIGGER update_vm_templates_modtime
BEFORE UPDATE ON vm_templates
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- vms (vcpu/memory replaced by richer columns; memory_hotplug constraint dropped)
CREATE TABLE IF NOT EXISTS vms (
    id                        UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name                      VARCHAR(50) UNIQUE NOT NULL,
    status                    vm_status NOT NULL,
    host_id                   UUID REFERENCES hosts(id),
    hypervisor                hypervisor NOT NULL,
    config                    JSONB NOT NULL,
    boot_source_id            UUID REFERENCES boot_sources(id),
    description               TEXT,
    boot_vcpus                INTEGER NOT NULL,
    max_vcpus                 INTEGER NOT NULL,
    cpu_topology              JSONB,
    kvm_hyperv                BOOLEAN DEFAULT false,
    memory_size               BIGINT NOT NULL,
    memory_hotplug_size       BIGINT,
    memory_mergeable          BOOLEAN DEFAULT false,
    memory_shared             BOOLEAN DEFAULT false,
    memory_hugepages          BOOLEAN DEFAULT false,
    memory_hugepage_size      BIGINT,
    memory_prefault           BOOLEAN DEFAULT false,
    memory_thp                BOOLEAN DEFAULT true,
    image_ref                 VARCHAR(512),
    boot_mode                 boot_mode NOT NULL DEFAULT 'KERNEL',
    cloud_init_user_data      TEXT,
    cloud_init_meta_data      TEXT,
    cloud_init_network_config TEXT,
    tags                      TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    created_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_boot_vcpus_max      CHECK (boot_vcpus <= max_vcpus),
    CONSTRAINT check_boot_vcpus_positive CHECK (boot_vcpus > 0),
    CONSTRAINT check_memory_size_positive CHECK (memory_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_vms_hypervisor   ON vms(hypervisor);
CREATE INDEX IF NOT EXISTS idx_vms_host_id      ON vms(host_id);
CREATE INDEX IF NOT EXISTS idx_vms_status       ON vms(status);
CREATE INDEX IF NOT EXISTS idx_vms_boot_source  ON vms(boot_source_id);
CREATE INDEX IF NOT EXISTS idx_vms_cpu_config   ON vms(boot_vcpus, max_vcpus);
CREATE INDEX IF NOT EXISTS idx_vms_memory       ON vms(memory_size);
CREATE INDEX IF NOT EXISTS idx_vms_memory_shared    ON vms(memory_shared)    WHERE memory_shared = true;
CREATE INDEX IF NOT EXISTS idx_vms_memory_hugepages ON vms(memory_hugepages) WHERE memory_hugepages = true;

CREATE TRIGGER update_vms_modtime
BEFORE UPDATE ON vms
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- network_interfaces (nullable network_id, mac_address, ip_address)
CREATE TABLE IF NOT EXISTS network_interfaces (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vm_id        UUID NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    network_id   UUID REFERENCES networks(id) ON DELETE CASCADE,
    mac_address  MACADDR,
    ip_address   INET,
    interface_type interface_type NOT NULL,
    device_id    VARCHAR(50) NOT NULL,
    tap_name     VARCHAR(50),
    host_mac     MACADDR,
    mtu          INTEGER DEFAULT 1500,
    vhost_user   BOOLEAN DEFAULT false,
    vhost_socket VARCHAR(255),
    vhost_mode   VARCHAR(20),
    num_queues   INTEGER DEFAULT 1,
    queue_size   INTEGER DEFAULT 256,
    rate_limiter JSONB,
    offload_tso  BOOLEAN DEFAULT true,
    offload_ufo  BOOLEAN DEFAULT true,
    offload_csum BOOLEAN DEFAULT true,
    pci_segment  INTEGER DEFAULT 0,
    iommu        BOOLEAN DEFAULT false,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT network_interfaces_vm_device_unique UNIQUE (vm_id, device_id),
    CONSTRAINT check_mtu_positive         CHECK (mtu > 0),
    CONSTRAINT check_num_queues_positive  CHECK (num_queues > 0),
    CONSTRAINT check_queue_size_positive  CHECK (queue_size > 0),
    CONSTRAINT check_vhost_socket         CHECK (
        (vhost_user = false) OR (vhost_user = true AND vhost_socket IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_network_interfaces_vm     ON network_interfaces(vm_id);
CREATE INDEX IF NOT EXISTS idx_network_interfaces_device ON network_interfaces(device_id);
CREATE INDEX IF NOT EXISTS idx_network_interfaces_vhost  ON network_interfaces(vhost_user) WHERE vhost_user = true;
CREATE INDEX IF NOT EXISTS idx_network_interfaces_network ON network_interfaces(network_id);

CREATE TRIGGER update_network_interfaces_modtime
BEFORE UPDATE ON network_interfaces
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- vm_disks (device_name → device_path → kept; disk_id → logical_name)
CREATE TABLE IF NOT EXISTS vm_disks (
    id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vm_id                 UUID NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    storage_object_id     UUID REFERENCES storage_objects(id),
    device_path           VARCHAR(20) NOT NULL,
    boot_order            INTEGER,
    read_only             BOOLEAN DEFAULT false,
    config                JSONB NOT NULL DEFAULT '{}'::jsonb,
    logical_name          VARCHAR(50) NOT NULL,
    direct                BOOLEAN DEFAULT false,
    vhost_user            BOOLEAN DEFAULT false,
    vhost_socket          VARCHAR(255),
    num_queues            INTEGER DEFAULT 1,
    queue_size            INTEGER DEFAULT 128,
    rate_limiter          JSONB,
    rate_limit_group      VARCHAR(100),
    pci_segment           INTEGER DEFAULT 0,
    serial_number         VARCHAR(100),
    upper_storage_object_id UUID REFERENCES storage_objects(id) ON DELETE SET NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vm_disks_vm_logical_name_unique UNIQUE (vm_id, logical_name),
    CONSTRAINT check_disk_path_or_vhost CHECK (
        (vhost_user = true AND vhost_socket IS NOT NULL) OR
        (vhost_user = false AND storage_object_id IS NOT NULL)
    ),
    CONSTRAINT check_num_queues_positive CHECK (num_queues > 0),
    CONSTRAINT check_queue_size_positive CHECK (queue_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_vm_disks_vm           ON vm_disks(vm_id);
CREATE INDEX IF NOT EXISTS idx_vm_disks_storage      ON vm_disks(storage_object_id);
CREATE INDEX IF NOT EXISTS idx_vm_disks_boot         ON vm_disks(boot_order) WHERE boot_order IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vm_disks_logical_name ON vm_disks(logical_name);
CREATE INDEX IF NOT EXISTS idx_vm_disks_vhost        ON vm_disks(vhost_user) WHERE vhost_user = true;
CREATE INDEX IF NOT EXISTS idx_vm_disks_rate_limit_group ON vm_disks(rate_limit_group) WHERE rate_limit_group IS NOT NULL;

-- vm_consoles
CREATE TABLE IF NOT EXISTS vm_consoles (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vm_id        UUID NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    console_type VARCHAR(20) NOT NULL,
    mode         console_mode NOT NULL,
    file_path    VARCHAR(255),
    socket_path  VARCHAR(255),
    iommu        BOOLEAN DEFAULT false,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vm_id, console_type)
);

CREATE INDEX IF NOT EXISTS idx_vm_consoles_vm   ON vm_consoles(vm_id);
CREATE INDEX IF NOT EXISTS idx_vm_consoles_type ON vm_consoles(console_type);

CREATE TRIGGER update_vm_consoles_modtime
BEFORE UPDATE ON vm_consoles
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- vm_rng
CREATE TABLE IF NOT EXISTS vm_rng (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vm_id      UUID NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    src        VARCHAR(255) NOT NULL DEFAULT '/dev/urandom',
    iommu      BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vm_id)
);

CREATE INDEX IF NOT EXISTS idx_vm_rng_vm ON vm_rng(vm_id);

CREATE TRIGGER update_vm_rng_modtime
BEFORE UPDATE ON vm_rng
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- rate_limit_groups
CREATE TABLE IF NOT EXISTS rate_limit_groups (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    vm_id      UUID REFERENCES vms(id) ON DELETE CASCADE,
    config     JSONB NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vm_id, name)
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_groups_vm   ON rate_limit_groups(vm_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_groups_name ON rate_limit_groups(name);

CREATE TRIGGER update_rate_limit_groups_modtime
BEFORE UPDATE ON rate_limit_groups
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- transfers (storage_object_id ON DELETE SET NULL, storage_pool_id ON DELETE CASCADE)
CREATE TABLE IF NOT EXISTS transfers (
    id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    transfer_type     transfer_type NOT NULL,
    status            transfer_status NOT NULL DEFAULT 'PENDING',
    source            TEXT NOT NULL,
    storage_pool_id   UUID REFERENCES storage_pools(id) ON DELETE CASCADE NOT NULL,
    object_type       storage_object_type NOT NULL,
    storage_object_id UUID REFERENCES storage_objects(id) ON DELETE SET NULL,
    total_bytes       BIGINT,
    transferred_bytes BIGINT DEFAULT 0,
    error_message     TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_at        TIMESTAMP WITHOUT TIME ZONE,
    completed_at      TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_transfers_storage_pool ON transfers(storage_pool_id);
CREATE INDEX IF NOT EXISTS idx_transfers_status       ON transfers(status);

-- jobs
CREATE TABLE IF NOT EXISTS jobs (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type     job_type NOT NULL,
    status       job_status NOT NULL DEFAULT 'PENDING',
    description  TEXT,
    resource_id  UUID,
    resource_type TEXT,
    progress     INTEGER CHECK (progress BETWEEN 0 AND 100),
    result       JSONB,
    error        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

-- vm_snapshots (refactored: snapshot_url removed, storage_object_id added)
CREATE TABLE IF NOT EXISTS vm_snapshots (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vm_id             UUID NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    storage_object_id UUID NOT NULL REFERENCES storage_objects(id) ON DELETE CASCADE,
    name              TEXT NOT NULL DEFAULT '',
    status            snapshot_status NOT NULL DEFAULT 'CREATING',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS vm_snapshots_vm_id_idx       ON vm_snapshots(vm_id);
CREATE INDEX IF NOT EXISTS vm_snapshots_storage_obj_idx ON vm_snapshots(storage_object_id);

-- host_networks
CREATE TABLE IF NOT EXISTS host_networks (
    host_id     UUID NOT NULL REFERENCES hosts(id) ON DELETE CASCADE,
    network_id  UUID NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    bridge_name VARCHAR(15) NOT NULL,
    PRIMARY KEY (host_id, network_id),
    UNIQUE (host_id, bridge_name)
);

-- ip_allocations
CREATE TABLE IF NOT EXISTS ip_allocations (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id   UUID NOT NULL REFERENCES networks(id) ON DELETE CASCADE,
    ip_address   INET NOT NULL,
    vm_id        UUID REFERENCES vms(id) ON DELETE SET NULL,
    allocated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (network_id, ip_address)
);

-- host_gpus
CREATE TABLE IF NOT EXISTS host_gpus (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    host_id       UUID NOT NULL REFERENCES hosts(id) ON DELETE CASCADE,
    pci_address   VARCHAR(20) NOT NULL,
    model         VARCHAR(255),
    vendor        VARCHAR(100),
    vram_bytes    BIGINT,
    iommu_group   INTEGER NOT NULL,
    vm_id         UUID REFERENCES vms(id) ON DELETE SET NULL,
    numa_node     INTEGER NOT NULL DEFAULT -1,
    discovered_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(host_id, pci_address)
);

CREATE INDEX IF NOT EXISTS idx_host_gpus_host      ON host_gpus(host_id);
CREATE INDEX IF NOT EXISTS idx_host_gpus_available ON host_gpus(host_id) WHERE vm_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_host_gpus_vm        ON host_gpus(vm_id) WHERE vm_id IS NOT NULL;

-- lifecycle_hooks
CREATE TABLE IF NOT EXISTS lifecycle_hooks (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    url         TEXT NOT NULL,
    secret      TEXT,
    scope       hook_scope NOT NULL DEFAULT 'GLOBAL',
    scope_value TEXT,
    events      TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT lifecycle_hooks_name_key UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_lifecycle_hooks_scope
    ON lifecycle_hooks (scope, scope_value)
    WHERE active = TRUE;

-- hook_executions
CREATE TABLE IF NOT EXISTS hook_executions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hook_id         UUID NOT NULL REFERENCES lifecycle_hooks(id) ON DELETE CASCADE,
    vm_id           UUID NOT NULL,
    previous_status TEXT NOT NULL,
    new_status      TEXT NOT NULL,
    status          hook_execution_status NOT NULL DEFAULT 'PENDING',
    attempt_count   INT NOT NULL DEFAULT 0,
    max_attempts    INT NOT NULL DEFAULT 5,
    next_retry_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload         JSONB NOT NULL,
    response_status INT,
    response_body   TEXT,
    last_error      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    delivered_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_hook_executions_pending
    ON hook_executions (next_retry_at)
    WHERE status = 'PENDING';

-- sandboxes
CREATE TABLE IF NOT EXISTS sandboxes (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vm_id            UUID NOT NULL UNIQUE REFERENCES vms(id) ON DELETE CASCADE,
    vm_template_id   UUID REFERENCES vm_templates(id) ON DELETE SET NULL,
    name             TEXT NOT NULL UNIQUE,
    status           sandbox_status NOT NULL DEFAULT 'PROVISIONING',
    idle_timeout_secs INT NOT NULL DEFAULT 300,
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sandboxes_status        ON sandboxes (status);
CREATE INDEX IF NOT EXISTS idx_sandboxes_last_activity ON sandboxes (last_activity_at) WHERE status = 'READY';

-- host_numa_nodes
CREATE TABLE IF NOT EXISTS host_numa_nodes (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    host_id      UUID NOT NULL REFERENCES hosts(id) ON DELETE CASCADE,
    node_id      INTEGER NOT NULL,
    cpu_list     TEXT NOT NULL DEFAULT '',
    memory_bytes BIGINT,
    distances    INTEGER[] NOT NULL DEFAULT '{}',
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (host_id, node_id)
);

CREATE INDEX IF NOT EXISTS idx_host_numa_nodes_host ON host_numa_nodes (host_id);
