# coding: utf-8

"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstallHost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'local_node_path': 'str',
        'fc_version': 'str'
    }

    attribute_map = {
        'local_node_path': 'local_node_path',
        'fc_version': 'fc_version'
    }

    def __init__(self, local_node_path=None, fc_version=None):  # noqa: E501
        """InstallHost - a model defined in Swagger"""  # noqa: E501
        self._local_node_path = None
        self._fc_version = None
        self.discriminator = None
        if local_node_path is not None:
            self.local_node_path = local_node_path
        if fc_version is not None:
            self.fc_version = fc_version

    @property
    def local_node_path(self):
        """Gets the local_node_path of this InstallHost.  # noqa: E501


        :return: The local_node_path of this InstallHost.  # noqa: E501
        :rtype: str
        """
        return self._local_node_path

    @local_node_path.setter
    def local_node_path(self, local_node_path):
        """Sets the local_node_path of this InstallHost.


        :param local_node_path: The local_node_path of this InstallHost.  # noqa: E501
        :type: str
        """

        self._local_node_path = local_node_path

    @property
    def fc_version(self):
        """Gets the fc_version of this InstallHost.  # noqa: E501


        :return: The fc_version of this InstallHost.  # noqa: E501
        :rtype: str
        """
        return self._fc_version

    @fc_version.setter
    def fc_version(self, fc_version):
        """Sets the fc_version of this InstallHost.


        :param fc_version: The fc_version of this InstallHost.  # noqa: E501
        :type: str
        """

        self._fc_version = fc_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstallHost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstallHost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
