# coding: utf-8

# flake8: noqa
"""
    Qarax API

    The API for Qarax manager  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.drive import Drive
from swagger_client.models.host import Host
from swagger_client.models.install_host import InstallHost
from swagger_client.models.kernel import Kernel
from swagger_client.models.storage import Storage
from swagger_client.models.vm import Vm
