/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 0.22.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// MmdsConfig : Defines the MMDS configuration.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MmdsConfig {
    /// A valid IPv4 link-local address.
    #[serde(rename = "ipv4_address", skip_serializing_if = "Option::is_none")]
    pub ipv4_address: Option<String>,
}

impl MmdsConfig {
    /// Defines the MMDS configuration.
    pub fn new() -> MmdsConfig {
        MmdsConfig { ipv4_address: None }
    }
}
