/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 0.22.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialDrive {
    #[serde(rename = "drive_id")]
    pub drive_id: String,
    /// Host level path for the guest drive
    #[serde(rename = "path_on_host")]
    pub path_on_host: String,
}

impl PartialDrive {
    pub fn new(drive_id: String, path_on_host: String) -> PartialDrive {
        PartialDrive {
            drive_id,
            path_on_host,
        }
    }
}
