/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 0.22.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotLoadParams {
    /// Enable support for incremental (diff) snapshots by tracking dirty guest pages.
    #[serde(
        rename = "enable_diff_snapshots",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_diff_snapshots: Option<bool>,
    /// Path to the file that contains the guest memory to be loaded.
    #[serde(rename = "mem_file_path")]
    pub mem_file_path: String,
    /// Path to the file that contains the microVM state to be loaded.
    #[serde(rename = "snapshot_path")]
    pub snapshot_path: String,
}

impl SnapshotLoadParams {
    pub fn new(mem_file_path: String, snapshot_path: String) -> SnapshotLoadParams {
        SnapshotLoadParams {
            enable_diff_snapshots: None,
            mem_file_path,
            snapshot_path,
        }
    }
}
