- name: set kvm permissions
  file:
    path: /dev/kvm
    mode: 0777
  become: yes

- name: check if start_fc.sh exists
  stat:
    path: ./start_fc.sh
  register: start_fc

- name: copy start_fc.sh to host
  copy:
    src: ../files/start_fc.sh
    dest: start_fc.sh
#    owner: "{{ ansible_user }}"
    mode: u=rwx
  when: not start_fc.stat.exists

- name: start vm
  shell: ./start_fc.sh &
